import Head from 'next/head'
import Link from 'next/link'

import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Card from '@/components/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>n13 child1 8081</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.common}`}>

        <h2>Child 1 App (Next 13 PORT 8081)</h2>
        <div className={`${styles.common}`}>
          <Link href="/blog">Go to Blog</Link>
        </div>

        <div className={`${styles.common}`}>
          <h3>Components</h3>
          <Card>Card 1</Card>
          <Button />
        </div>
      </main>
    </>
  )
}
